(* This file was autogenerated; don't edit it by hand *)

let tests () = OUnit.TestList [
    Async_gc.ounit_tests ();
    Async_print.ounit_tests ();
    Async_sys.ounit_tests ();
    Epoll_file_descr_watcher.ounit_tests ();
    Fd.ounit_tests ();
    Fd_by_descr.ounit_tests ();
    File_descr_watcher_intf.ounit_tests ();
    Import.ounit_tests ();
    Interruptor.ounit_tests ();
    In_thread.ounit_tests ();
    Io_stats.ounit_tests ();
    Raw_fd.ounit_tests ();
    Raw_scheduler.ounit_tests ();
    Raw_signal_manager.ounit_tests ();
    Reader.ounit_tests ();
    Read_write.ounit_tests ();
    Scheduler.ounit_tests ();
    Select_file_descr_watcher.ounit_tests ();
    Shutdown.ounit_tests ();
    Signal.ounit_tests ();
    Signal_manager.ounit_tests ();
    Std.ounit_tests ();
    Syscall.ounit_tests ();
    Thread_safe.ounit_tests ();
    Unix_syscalls.ounit_tests ();
    Work_group.ounit_tests ();
    Writer.ounit_tests ();
];;

let run () =  ignore (OUnit.run_test_tt_main (tests ()):OUnit.test_result list)
